### ISSUE TITLE
Dynamic buttons

### ISSUE THREAD

**Issue by Rufasa85** [Rufasa85/animal-search#2]
## Task:
I want lots of animal buttons based on my favorite animals

## Acceptance:
- [ ] page starts with dog and cat buttons
- [ ] input field for adding new buttons
- [ ] new button appended next to old buttons
- [ ] click events work for both static and dynamic buttons
